#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &


terminal="ghosty"  # Replace with your terminal


dex --autostart --environment bspwm &
picom &
nm-applet &
feh --bg-fill ~/.config/wallpapers/sunset.png &
/sbin/kanata -c ~/.config/kanata/config.kbd &
~/.config/polybar/launch.sh &
xborders -c ~/.config/xborders/config.json &

export XCURSOR_THEME="Breeze"
export XCURSOR_SIZE=24
xsetroot -cursor_name left_ptr

#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focus_follows_pointer true


bspc config border_width         0
bspc config window_gap          10
bspc config top_padding         32

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a '*xborders*' state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a discord desktop=^1
bspc rule -a steam desktop=^5
bspc rule -a heroic desktop=^9




bspc rule -a steam_app_0 state=floating
(sxhkd &)
(ghostty &)
(discord &)
(steam &)
