# exec-once = $terminal
exec-once = hyprpaper &
exec-once = nm-applet &
exec-once = bash -c "sleep 1 && waybar"
#exec-once = steam
exec-once = discord &
exec-once = wal -i ~/.config/background/naboo.png
