;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]

background = #FA232723
background-alt = #373B41
foreground = #C5CaC6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #686868
nocolor = #000000AA


[bar/workspaces]
modules-left = spaceholder bspwm
override-redirect = true
width = 16%
height = 26pt

offset-x = 0.5%
offset-y = 4

include-file = ~/.config/polybar/theme.ini

[bar/window]
modules-left = spaceholder xwindow
override-redirect = true
width = 8%
height = 26pt

offset-x = 17%
offset-y = 4

include-file = ~/.config/polybar/theme.ini

[bar/center]
modules-center = date 

override-redirect = true

width = 10.5%
height = 26pt

offset-x = 44.75%
offset-y = 4

include-file = ~/.config/polybar/theme.ini

[bar/control]
modules-left = spaceholder spaceholder bluetooth pulseaudio separator2 network
override-redirect = true
width = 13%
height = 26pt
offset-x = 57%
offset-y = 4
include-file = ~/.config/polybar/theme.ini

[bar/info]
modules-right = spaceholder memory separator cpu separator gpu separator battery separator power
override-redirect = true
width = 29%
height = 26pt
offset-x = 70.5%
offset-y = 4
include-file = ~/.config/polybar/theme.ini

[bar/extra]
modules-left = spaceholder updates separator polypomo
override-redirect = true
width = 10%
height = 26pt
offset-x = 29.25%
offset-y = 4
include-file = ~/.config/polybar/theme.ini

[section/modules]
include-file = ~/.config/polybar/modules.ini

[settings]
screenchange-reload = true
pseudo-transparency = true

[global/wm]
margin-top = 0
margin-bottom = 0
; vim:ft=dosini

