[module/bspwm]
type = internal/bspwm


enable-click = true
enable-scroll = true
reverse-scroll = false

fuzzy-match = true

ws-icon-0=I;
ws-icon-1=II;
ws-icon-2=III;
ws-icon-3=IV;
ws-icon-4=V;
ws-icon-5=VI;
ws-icon-6=VII;VII
ws-icon-7=VIII;VIII
ws-icon-8=IX;IX
ws-icon-9=X;X
ws-icon-default = 
format = <label-state>
format-font = 1
#
label-monitor = %icon%

label-focused = %icon%
label-focused-foreground = ${color.foreground}
label-focused-background = #393d39
label-focused-padding = 5px 

label-occupied = %{T8}%icon%%{T-}
;label-occupied-background = #303030
label-occupied-padding = 5px

label-urgent = %icon%
label-urgent-foreground = ${color.red}
label-urgent-underline =  ${color.red}
label-urgent-padding = 5px

label-empty = %{T8}%icon%%{T8}
label-empty-foreground = #686868 
label-empty-padding = 5px

; Separator in between workspaces
label-separator = ""
label-separator-padding = 0
label-separator-background = ${color.SHADE4} 


[module/xworkspaces]
type = internal/xworkspaces
enable-click = true
enable-scroll = true

label-active = "%name%"
label-active-foreground = ${colors.foreground}
label-active-padding = 4px
label-active-background = #393d39
;label-active-underline=rgba(206, 218, 233, 0.48)

label-occupied = "%{T8}%name%%{T-}"
label-occupied-padding = 4px

label-urgent = "%{T8}%name%%{T-}"
label-urgent-foreground1 = ${colors.alert}
label-urgent-padding = 4px

label-empty = "%{T8}%name%%{T-}"
label-empty-foreground = ${colors.disabled}
label-empty-padding = 4px


[module/separator]
type = custom/text
content = "  |  "
content-foreground = ${colors.foreground}

[module/separator2]
type = custom/text
content = "|  "
content-foreground = ${colors.foreground}

[module/spaceholder]
type = custom/text
content = " "


[module/test]
type = custom/script
exec = ~/.config/polybar/polybar-scripts/workspaces.sh
tail = true

[module/updates]
type = custom/script
exec = ~/.config/polybar/polybar-scripts/updates_polybar.sh
click-right = alacritty -e ~/scripts/update.sh
interval = 300

[module/polypomo]
type = custom/script

exec = ~/.config/polybar/polybar-scripts/pomodoro.py
tail = true

label = %output%
click-left = ~/.config/polybar/polybar-scripts/pomodoro.py toggle
click-right = ~/.config/polybar/polybar-scripts/pomodoro.py end
click-middle = ~/.config/polybar/polybar-scripts/pomodoro.py lock
scroll-up = ~/.config/polybar/polybar-scripts/pomodoro.py time +60
scroll-down = ~/.config/polybar/polybar-scripts/pomodoro.py time -60



[module/cpu]
type = custom/script
interval = 2
;format-underline = ${colors.cpuAccent}
format-prefix = "%{F#e06c75}%{F} "
format-prefix-foreground = ${colors.primary}

exec = echo "$(printf "%3s" "$[100-$(vmstat 1 2 | tail -1 | awk '{print $15}')]")% $(sensors coretemp-isa-0000 | grep -A 0 'Package id 0' | cut -c17-18)°C"
format-suffix = ""

click-right = alacritty -e btop

[module/gpu]
type = custom/script
interval = 2

;format-underline = ${colors.gpuAccent}
format-prefix = "%{F#98c379} %{F}"
exec = echo "$(printf "%3s" "$(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits)")% $(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits)°C"

format-suffix = ""
click-right = alacritty -e watch nvidia-smi

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt


[module/favorites]
type = custom/text
;content-underline = ${colors.favoritesAccent}
;using action formatting tag to define clickable areas
content = "%{A1:alacritty&:}%{A}  %{A1:firefox&:}%{A}  %{A1:discord&:}%{A}  %{A1:steam&:}%{A}"

[module/xwindow]
type = internal/xwindow
label = " %{F#c9ab55} %{F} %class%"
label-empty = " %{F#c9ab55} %{F} No Window"


label-maxlen = 27
interval = 0.5
padding = 2

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix =
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = " %percentage%%    "
label-volume-maxlen = 6
label-volume-ellipsis = false
label-muted = "mute  " 
label-muted-foreground = ${colors.disabled}

click-right = blueman-manager

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/polybar-scripts/bluetooth-headphones.sh
click-right = blueman-manager
tail = true

[module/power]
type = custom/text
label = " "
click-left = bash $HOME/.config/rofi/powermenu.sh


[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "%{F#e5c07b}%{F} "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/network]
type = custom/script
exec = ~/.config/polybar/polybar-scripts/network_status.sh
interval = 5
label = %output%
label-maxlen = 28
click-right = alacritty -e nmtui

[module/date]
type = internal/date
interval = 1
date = "%a %d %b" 
date-alt = "%d %b" 
time = "%H:%M"
time-alt = %H:%M:%S
;format-underline = ${colors.dateAccent}
format-prefix = "%{F#61afef}  %{F}"
label = %date% %time%
format-suffix = ""

[module/battery]
type = internal/battery

full-at = 99
low-at = 15

battery = BAT1
adapter = ADP1

poll-interval = 5
time-format = %H:%M

format-charging = %{F#239e29}<animation-charging>%{F}  <label-charging>
format-discharging = <ramp-capacity>  <label-discharging>
format-low = <animation-low>  <label-low>
format-full = %{F#157543}<ramp-capacity>%{F} <label-full>

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = %percentage%%
label-low = %percentage%%

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = "%{F#e39d2d}%{F}"
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 

; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 

; Framerate in milliseconds
animation-discharging-framerate = 500

; Only applies if <animation-low> is used
animation-low-0 = "%{F#A54242}!%{F}"
animation-low-1 = " "
animation-low-framerate = 500
