
line-size = 2
line-color = #f00
; dpi = 96

fixed-center = true
background = ${colors.background}

border-size = 0pt
border-color = ${colors.background}
foreground = ${colors.foreground}

enable-ips = true
wm-restack = bspwm

radius = 8

padding-left = 0
padding-right = 1

module-margin = 0

font-0 = monospace:style=Bold:size=11;3

font-1 = fixed:pixelsize= 11;1
font-2 = unifont:fontformat=truetype:size=0:antialias=true;3
font-3 = Font Awesome 6 Free Regular:pixelsize=11;3
font-4 = Font Awesome 6 Free Solid:pixelsize=11;3
font-5 = Font Awesome 6 Brands Regular:pixelsize=11;3
font-6 = icomoon:pixelsize=28;1
font-7 = monospace:size=11;3

enable-ipc = true
bottom = false

#click-right = code ~/.config/polybar/config.ini
